import { ThemeConfig } from "./config/theme.config"
import { NotificationProvider } from "./context/notification.context"


export const metadata = {
  title: 'SharpSightApp',
  description: 'Generated by Carlos Ivan Munoz',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {

  return (
    <html lang="en">
      <ThemeConfig>
        <NotificationProvider>
          <body>
            {children}
          </body>
        </NotificationProvider>
      </ThemeConfig>
    </html>
  )
}
