// import './globals.css'
// import { Inter } from 'next/font/google'

import { ThemeConfig } from "./theme.config"

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DataStructures',
  description: 'Generated by Carlos Ivan Munoz',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <ThemeConfig>
      <html lang="en">
        <body >
          {children}
        </body>
      </html>
    </ThemeConfig>
  )
}
